### ISSUE TITLE
Gör kort av produkter på startsida

### ISSUE THREAD

**Issue by felixwetell** [Kakelplattan-1/flytspackel.com#8]

**Comment by Kakelplattan** [comment]
Har laddat upp sidan på kakelverktyg. En enkel och lätt cookies hade du, kan du lägga till den?

Dagens industri hade denna:

Vi använder cookies för att förbättra funktionaliteten på våra sajter, för att kunna rikta relevant innehåll och annonser till dig och för att vi ska kunnasäkerställa att tjänsterna fungerar som de ska. Läs mer i vår cookiepolicy.

**Comment by Kakelplattan** [comment]
Ska ändra på bilderna för förstasidan.

**Comment by Kakelplattan** [comment]
Om jag ändrar i koden, var ska jag lägga den så du har senaste?

**Comment by felixwetell** [comment]
@Kakelplattan jag har lagt upp en issue på det, se issue #9. 

Se denna guide för att komma igång med git och GitHub: https://help.github.com/en/desktop/getting-started-with-github-desktop
